services:
  next-app:
    build:
      context: ./web-auth
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

  streamlit-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    restart: always
