# .streamlit/secrets.toml
SUPABASE_URL = "https://rdzgzvyxlaszygxchzlp.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkemd6dnl4bGFzenlneGNoemxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3ODg0MzEsImV4cCI6MjA4NTM2NDQzMX0.NBQvzCzMYvUkxFQNR06gOK9otavlDKh3b9U4se5mEBA"